### ISSUE TITLE
Unable to run "darknet" command

### ISSUE THREAD

**Issue by nbandaru1h** [hank-ai/darknet#92]
I have followed build instructions just as given. 
```
make -j4 package

-- Darknet v3.0-195-gb4b25d33-dirty
-- CUDA detected. Darknet will use the GPU.
-- Found cuDNN library: /usr/local/cuda/lib64/libcudnn.so
-- Found cuDNN include: /usr/local/cuda/include
-- Hardware is 32-bit or 64-bit, and seems to be Intel or AMD:  x86_64
-- Found Threads 
CMake Warning (dev) at /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake:86 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

Call Stack (most recent call first):
  /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake:108 (find_host_package)
  CM_dependencies.cmake:126 (FIND_PACKAGE)
  CMakeLists.txt:33 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenCV 4.10.0
-- Found OpenMP 
-- Enabling AVX and SSE optimizations.
-- Making an optimized release build.
-- Setting up DARKNET OBJ
-- Setting up DARKNET LIB
-- Setting up DARKNET CLI
-- Setting up DARKNET examples
-- Configuring done (0.1s)
-- Generating done (0.1s)
-- Build files have been written to: /home/nbandaru1/src/darknet/build
[  1%] Building CUDA object src-lib/CMakeFiles/darknetobjlib.dir/avgpool_layer_kernels.cu.o
[  3%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/col2im.cpp.o
[  3%] Building CUDA object src-lib/CMakeFiles/darknetobjlib.dir/blas_kernels.cu.o
[  4%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/box.cpp.o
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
[  5%] Building CUDA object src-lib/CMakeFiles/darknetobjlib.dir/col2im_kernels.cu.o
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
[  7%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/connected_layer.cpp.o
[  8%] Building CUDA object src-lib/CMakeFiles/darknetobjlib.dir/convolutional_kernels.cu.o
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
[  9%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/convolutional_layer.cpp.o
[ 10%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/cost_layer.cpp.o
[ 11%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/crnn_layer.cpp.o
[ 12%] Building CUDA object src-lib/CMakeFiles/darknetobjlib.dir/crop_layer_kernels.cu.o
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
[ 14%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/dark_cuda.cpp.o
[ 15%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/darknet.cpp.o
[ 16%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/darknet_args_and_parms.cpp.o
[ 17%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/darknet_cfg.cpp.o
[ 18%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/darknet_cfg_and_state.cpp.o
[ 20%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/darknet_enums.cpp.o
[ 21%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/darknet_format_and_colour.cpp.o
[ 22%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/darknet_image.cpp.o
[ 23%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/darknet_keypoints.cpp.o
[ 24%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/darknet_network.cpp.o
[ 25%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/darknet_utils.cpp.o
[ 27%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/data.cpp.o
[ 28%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/detector.cpp.o
[ 29%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/dropout_layer.cpp.o
[ 30%] Building CUDA object src-lib/CMakeFiles/darknetobjlib.dir/dropout_layer_kernels.cu.o
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
[ 31%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/dump.cpp.o
[ 32%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/gaussian_yolo_layer.cpp.o
[ 34%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/gemm.cpp.o
[ 35%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/im2col.cpp.o
[ 36%] Building CUDA object src-lib/CMakeFiles/darknetobjlib.dir/im2col_kernels.cu.o
[ 37%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/image_opencv.cpp.o
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
[ 38%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/layer.cpp.o
[ 40%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/list.cpp.o
[ 41%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/lstm_layer.cpp.o
[ 42%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/matrix.cpp.o
[ 43%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/maxpool_layer.cpp.o
[ 44%] Building CUDA object src-lib/CMakeFiles/darknetobjlib.dir/maxpool_layer_kernels.cu.o
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
[ 45%] Building CUDA object src-lib/CMakeFiles/darknetobjlib.dir/network_kernels.cu.o
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
[ 47%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/nightmare.cpp.o
[ 48%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/option_list.cpp.o
[ 49%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/region_layer.cpp.o
[ 50%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/reorg_layer.cpp.o
[ 51%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/rnn_layer.cpp.o
[ 52%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/route_layer.cpp.o
[ 54%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/sam_layer.cpp.o
[ 55%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/scale_channels_layer.cpp.o
[ 56%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/shortcut_layer.cpp.o
[ 57%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/softmax_layer.cpp.o
[ 58%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/tree.cpp.o
[ 60%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/upsample_layer.cpp.o
[ 61%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/utils.cpp.o
[ 62%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/weights.cpp.o
[ 63%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/yolo_layer.cpp.o
[ 64%] Building CXX object src-lib/CMakeFiles/darknetobjlib.dir/yolo_v2_class.cpp.o
[ 72%] Built target darknetobjlib
[ 74%] Building CXX object src-cli/CMakeFiles/darknetcli.dir/darknet_cli.cpp.o
[ 75%] Linking CXX shared library libdarknet.so
[ 76%] Linking CXX executable darknet
[ 76%] Built target darknet
[ 77%] Building CXX object src-examples/CMakeFiles/darknet_02_display_annotated_images.dir/darknet_02_display_annotated_images.cpp.o
[ 78%] Building CXX object src-examples/CMakeFiles/darknet_01_inference_images.dir/darknet_01_inference_images.cpp.o
[ 80%] Building CXX object src-examples/CMakeFiles/darknet_03_display_videos.dir/darknet_03_display_videos.cpp.o
[ 81%] Linking CXX executable darknet_01_inference_images
[ 82%] Linking CXX executable darknet_03_display_videos
[ 83%] Linking CXX executable darknet_02_display_annotated_images
[ 83%] Built target darknet_01_inference_images
[ 84%] Building CXX object src-examples/CMakeFiles/darknet_04_process_videos.dir/darknet_04_process_videos.cpp.o
[ 84%] Built target darknet_03_display_videos
[ 85%] Building CXX object src-examples/CMakeFiles/darknet_05_process_videos_multithreaded.dir/darknet_05_process_videos_multithreaded.cpp.o
[ 85%] Built target darknet_02_display_annotated_images
[ 87%] Building CXX object src-examples/CMakeFiles/darknet_06_images_to_json.dir/darknet_06_images_to_json.cpp.o
[ 87%] Built target darknetcli
[ 88%] Building CXX object src-examples/CMakeFiles/darknet_07_display_rtsp_stream.dir/darknet_07_display_rtsp_stream.cpp.o
[ 89%] Linking CXX executable darknet_04_process_videos
[ 90%] Linking CXX executable darknet_05_process_videos_multithreaded
[ 90%] Built target darknet_04_process_videos
[ 91%] Building CXX object src-examples/CMakeFiles/darknet_08_display_webcam.dir/darknet_08_display_webcam.cpp.o
[ 92%] Linking CXX executable darknet_07_display_rtsp_stream
[ 92%] Built target darknet_05_process_videos_multithreaded
[ 94%] Building CXX object src-examples/CMakeFiles/darknet_09_keypoints_images.dir/darknet_09_keypoints_images.cpp.o
[ 94%] Built target darknet_07_display_rtsp_stream
[ 95%] Building CXX object src-examples/CMakeFiles/darknet_10_keypoints_videos.dir/darknet_10_keypoints_videos.cpp.o
[ 96%] Linking CXX executable darknet_06_images_to_json
[ 97%] Linking CXX executable darknet_08_display_webcam
[ 97%] Built target darknet_06_images_to_json
[ 97%] Built target darknet_08_display_webcam
[ 98%] Linking CXX executable darknet_09_keypoints_images
[100%] Linking CXX executable darknet_10_keypoints_videos
[100%] Built target darknet_09_keypoints_images
[100%] Built target darknet_10_keypoints_videos
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: Darknet
CPack: - Install project: Darknet []
CPack: Create package
CPackDeb: - Generating dependency list
CPack: - package: /home/nbandaru1/src/darknet/build/darknet-3.0.195-Linux.deb generated.
```

```
make -j4 package

[ 72%] Built target darknetobjlib
[ 74%] Built target darknet
[ 76%] Built target darknetcli
[ 78%] Built target darknet_02_display_annotated_images
[ 82%] Built target darknet_01_inference_images
[ 83%] Built target darknet_03_display_videos
[ 85%] Built target darknet_04_process_videos
[ 91%] Built target darknet_06_images_to_json
[ 91%] Built target darknet_07_display_rtsp_stream
[ 92%] Built target darknet_05_process_videos_multithreaded
[ 95%] Built target darknet_08_display_webcam
[ 97%] Built target darknet_10_keypoints_videos
[100%] Built target darknet_09_keypoints_images
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: Darknet
CPack: - Install project: Darknet []
CPack: Create package
CPackDeb: - Generating dependency list
CPack: - package: /home/nbandaru1/src/darknet/build/darknet-3.0.195-Linux.deb generated.
```
```
sudo dpkg -i darknet-3.0.195-Linux.deb

(Reading database ... 686541 files and directories currently installed.)
Preparing to unpack darknet-3.0.195-Linux.deb ...
Unpacking darknet (3.0.195) over (3.0.195) ...
Setting up darknet (3.0.195) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
```

```
nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
```
```
nvidia-smi

Mon Nov 18 15:21:08 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A3000 Laptop GPU    Off | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P8              13W /  35W |     11MiB /  6144MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1540      G   /usr/lib/xorg/Xorg                            4MiB |
+---------------------------------------------------------------------------------------+
```
**ERROR:**

```
~/src/darknet/build$ darknet

CUDA status error: /home/nbandaru1/src/darknet/src-lib/dark_cuda.cpp, cuda_set_device(), line #29

* * * * * * * * * * * * * * * * * * * * * * * * * * * * *
* Errno 9: Bad file descriptor
* Error location: /home/nbandaru1/src/darknet/src-lib/dark_cuda.cpp, cuda_set_device(), line #29
*** Error message:  current CUDA error: status=999 cudaErrorUnknown: unknown error**
* Thread #139882553249792: main darknet thread
* Version v3.0-195-gb4b25d33-dirty built on Nov 18 2024 15:18:42
* * * * * * * * * * * * * * * * * * * * * * * * * * * * *
backtrace (8 entries):
1/8: darknet(_Z13log_backtracev+0x36) [0x55884b2def96]
2/8: darknet(_Z19darknet_fatal_errorPKcS0_iS0_z+0x673) [0x55884b2e0833]
3/8: darknet(+0x70229) [0x55884b21e229]
4/8: darknet(_Z25check_cuda_error_extended9cudaErrorPKcS1_i+0x105) [0x55884b21e3a5]
5/8: darknet(main+0x1a4) [0x55884b1edd44]
6/8: /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f3943570d90]
7/8: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f3943570e40]
8/8: darknet(_start+0x25) [0x55884b1f1585]
known threads:  1
1/1: #139882553249792: main darknet thread
Aborted (core dumped)
```

**Comment by stephanecharette** [comment]
See the many warnings in your build:

> nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used

The NVIDIA compiler did not detect a GPU.

**Comment by stephanecharette** [comment]
Also, your version field tells me you have local modifications to the repo:

> Version v3.0-195-gb4b25d33-dirty

Can you run `git status` to show what has been locally modified?  Also try `git diff` and see if the changes are something you remember doing.

**Comment by nbandaru1h** [comment]
I haven't modified anything actually - just cloned your repo and built it
When I encountered this error, I added a flag to CMakeLists.txt so it could maybe recognize the CUDA_ARCH_BIN. But of course, it didn't work. 

```
git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   CMakeLists.txt

no changes added to commit (use "git add" and/or "git commit -a")

```

**Comment by stephanecharette** [comment]
You could of course try to hard-code the GPU to use and see if that makes a difference.  See `DARKNET_CUDA_ARCHITECTURES` in CM_dependencies.cmake.

But the fact that nvcc is reporting that it cannot find a GPU, and then Darknet fails to set the GPU to use, is a pretty big hint that something is wrong with the NVIDIA drivers.

Two different things are telling you a GPU cannot be accessed (or found?).

**Comment by nbandaru1h** [comment]
Hmm....that's funny because when I run darknet training with Alexey repo normally it would find the GPU and train with it. But, I agree that there's something wrong. 
What is the valid syntax for the architecture? Compute_8.6 is invalid according to this build error:
```
nvcc fatal   : Unsupported gpu architecture 'compute_8.6'
make[2]: *** [src-lib/CMakeFiles/darknetobjlib.dir/build.make:111: src-lib/CMakeFiles/darknetobjlib.dir/activation_kernels.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/nbandaru1/src/darknet/build'
make[1]: *** [CMakeFiles/Makefile2:262: src-lib/CMakeFiles/darknetobjlib.dir/all] Error 2
make[1]: Leaving directory '/home/nbandaru1/src/darknet/build'
make: *** [Makefile:159: all] Error 2
```

**Comment by nbandaru1h** [comment]
That fixed the build, but the error persists:
```
darknet
CUDA status error: /home/nbandaru1/src/darknet/src-lib/dark_cuda.cpp, cuda_set_device(), line #29

* * * * * * * * * * * * * * * * * * * * * * * * * * * * *
* Errno 9: Bad file descriptor
* Error location: /home/nbandaru1/src/darknet/src-lib/dark_cuda.cpp, cuda_set_device(), line #29
* Error message:  current CUDA error: status=999 cudaErrorUnknown: unknown error
* Thread #139981998850048: main darknet thread
* Version v3.0-195-gb4b25d33-dirty built on Nov 18 2024 16:04:07
* * * * * * * * * * * * * * * * * * * * * * * * * * * * *
backtrace (8 entries):
1/8: darknet(_Z13log_backtracev+0x36) [0x55a718568f96]
2/8: darknet(_Z19darknet_fatal_errorPKcS0_iS0_z+0x673) [0x55a71856a833]
3/8: darknet(+0x70229) [0x55a7184a8229]
4/8: darknet(_Z25check_cuda_error_extended9cudaErrorPKcS1_i+0x105) [0x55a7184a83a5]
5/8: darknet(main+0x1a4) [0x55a718477d44]
6/8: /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f5068d70d90]
7/8: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f5068d70e40]
8/8: darknet(_start+0x25) [0x55a71847b585]
known threads:  1
1/1: #139981998850048: main darknet thread
Aborted (core dumped)
```

**Comment by stephanecharette** [comment]
After you built it, did you remember to install it?  If not, you're still running the old one you build before you hard-coded the GPU value.

**Comment by stephanecharette** [comment]
Do you have multiple GPUs?  If you look at the function cuda_set_device() in dark_cuda.cpp on line 29, you'll see there really is not much to it.  It is a single CUDA call to set which GPU to use.

What is the output of `darknet --version`?  Does it see the GPU?

**Comment by nbandaru1h** [comment]
Should I be doing a make install as well?

```
~/src/darknet/build$ make install
[ 72%] Built target darknetobjlib
[ 74%] Built target darknet
[ 76%] Built target darknetcli
[ 78%] Built target darknet_01_inference_images
[ 81%] Built target darknet_02_display_annotated_images
[ 83%] Built target darknet_03_display_videos
[ 85%] Built target darknet_04_process_videos
[ 88%] Built target darknet_05_process_videos_multithreaded
[ 90%] Built target darknet_06_images_to_json
[ 92%] Built target darknet_07_display_rtsp_stream
[ 95%] Built target darknet_08_display_webcam
[ 97%] Built target darknet_09_keypoints_images
[100%] Built target darknet_10_keypoints_videos
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /opt/darknet/cfg/Gaussian_yolov3_BDD.cfg
CMake Error at cfg/cmake_install.cmake:54 (file):
  file INSTALL cannot set permissions on
  "/opt/darknet/cfg/Gaussian_yolov3_BDD.cfg": Operation not permitted.
Call Stack (most recent call first):
  cmake_install.cmake:52 (include)


make: *** [Makefile:120: install] Error 1
```
:~/src/darknet/build$ darknet --version
CUDA status error: /home/nbandaru1/src/darknet/src-lib/dark_cuda.cpp, cuda_set_device(), line #29

* * * * * * * * * * * * * * * * * * * * * * * * * * * * *
* Errno 9: Bad file descriptor
* Error location: /home/nbandaru1/src/darknet/src-lib/dark_cuda.cpp, cuda_set_device(), line #29
* Error message:  current CUDA error: status=999 cudaErrorUnknown: unknown error
* Thread #140468877402112: main darknet thread
* Version v3.0-195-gb4b25d33-dirty built on Nov 19 2024 10:55:51
* * * * * * * * * * * * * * * * * * * * * * * * * * * * *
backtrace (8 entries):
1/8: darknet(_Z13log_backtracev+0x36) [0x55b001753f96]
2/8: darknet(_Z19darknet_fatal_errorPKcS0_iS0_z+0x673) [0x55b001755833]
3/8: darknet(+0x70229) [0x55b001693229]
4/8: darknet(_Z25check_cuda_error_extended9cudaErrorPKcS1_i+0x105) [0x55b0016933a5]
5/8: darknet(main+0x1a4) [0x55b001662d44]
6/8: /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fc1c6f70d90]
7/8: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fc1c6f70e40]
8/8: darknet(_start+0x25) [0x55b001666585]
known threads:  1
1/1: #140468877402112: main darknet thread
Aborted (core dumped)
```

**Comment by nbandaru1h** [comment]
Thanks for your help, appreciate it!

**Comment by stephanecharette** [comment]
> CMake Error at cfg/cmake_install.cmake:54 (file):
>   file INSTALL cannot set permissions on
>   "/opt/darknet/cfg/Gaussian_yolov3_BDD.cfg": Operation not permitted.

Sorry, never heard of this error before.  I have no idea what you've done.

**Comment by stephanecharette** [comment]
No activity.  Closing.
